export function generateMap(fileName, language, functions) {
  const now = new Date();
  const dateStr = now.toISOString().split('T')[0];
  const timestamp = now.toISOString().replace('T', ' ').substring(0, 19);
  const documentedCount = functions.filter(f => f.docstring).length;

  let md = `# MapME: ${fileName}\n`;
  md += `**Language:** ${language.charAt(0).toUpperCase() + language.slice(1)}\n`;
  md += `**Scanned:** ${dateStr}\n`;
  md += `**Total Symbols:** ${functions.length}\n`;
  md += `**Documented:** ${documentedCount} / ${functions.length}\n\n`;
  md += `---\n\n`;

  for (const fn of functions) {
    let typeStr;
    if (fn.isClass) {
      typeStr = fn.isExported ? 'exported class' : 'class';
    } else if (fn.isConstructor) {
      typeStr = 'constructor';
    } else {
      const parts = [];
      if (fn.isAsync) parts.push('async');
      if (fn.isArrow) parts.push('arrow function');
      else parts.push('function');
      typeStr = parts.join(' ');
    }

    md += `## \`${fn.name}(${fn.params})\`\n`;
    md += `- **Type:** ${typeStr}\n`;
    md += `- **Exported:** ${fn.isExported ? 'Yes' : 'No'}\n`;
    md += `- **Line:** ${fn.lineNumber}\n`;
    if (fn.docstring) {
      const cleanDoc = fn.docstring.replace(/\n/g, ' ');
      md += `- **Docs:** ${cleanDoc}\n`;
    } else {
      md += `- **Docs:** *(no documentation found)*\n`;
    }
    md += '\n';
  }

  md += `---\n*Generated by MapME v1.0 — ${timestamp}*\n`;
  return md;
}